language: rust
jobs:
  include:
  - os: linux
    rust:
    - stable
    - beta
    - nightly
    allow_failures:
    - rust: nightly
    addons:
      apt:
        packages: lua5.3
    before_install: 'mkdir bin; cd bin; export PATH=$(pwd):$PATH; ln -s $(which lua5.3)
      lua; which lua;

'
  - os: osx
    before_install: 'brew update; brew install lua;

'
  - os: windows
    before_install: 'choco install lua53; mkdir bin; cd bin; export PATH=/c/ProgramData/chocolatey/lib/lua53/tools/:$PATH;
      cp /c/ProgramData/chocolatey/lib/lua53/tools/lua53 /c/ProgramData/chocolatey/lib/lua53/tools/lua;
      ls /c/ProgramData/chocolatey/lib/lua53/tools/;

'
  fast_finish: true
cache: cargo

deploy:
  provider: releases
  api_key:
    secure: NAmjiTur0R70FEuvJjlXyVGWgdCVoypPENIblfsDdawxjyV3AMQok0Kq8KnOPTe2dhPYLnPSMdT//XxA01c8ieZ/RfyH4LCD52zPs4NWL9/XFEnUoGlv3yJUEhPeugUXtSF+Y5mdi7WdrY5AJiWhXS2za2OlqOU0dPzNU3uNxjxI8Cv/NGCxR5syYlBGBXkpTD1i/Z814hi/LmD+zbprzZriRAuYeaBtObHb0zwHfgAQt66Dock3gc3BAF52f1g4dElyPqiZ7qef9Wos134lfKlMeUGxM42baf9cEdqK6FvUfVEKE0lviuTNdrSJG53hgDBQg8pB8Dcf4ln6vgoywhBT4+zhv80S3CIKGoKDQI68RzbV2czuMtWcJa5bW0L8Xn7MdFX0Ry5qKrIqYjM8+PhH3Bo9Uf8DEVoY+G2NQXQUCGX/A0CElEOBMC/OANuwWvxwEKx3KvnBb21Ho6yUiUoE6mvugttGO0GyDljknIwq39j6UBOKnGK3Kyr4G2V0xDZEShTkwz3IlZMxES6j0FGbTgG+/qGpFMoFFwNhBDncwIceabnuZbuxK3EJGJjRbi8x7ROhkgX50ptDhq1uadEHBpCv36Dx7fFRjw1RZfnL8L2LZwlyH3b8F1VC9g1gULkPPtZpxUvLlW8kpLHA0jzML3coKey/MDwXWcY/f4o=
  file_glob: true
  file: lua-vfs-$TRAVIS_TAG-$TARGET.*
  on:
    repo: Ayplow/Lua-VFS
    tags: true
  skip_cleanup: true
