language: rust
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
os:
- linux
- osx
- windows
addons:
  apt:
    packages:
       lua5.3
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install lua; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install lua53; mkdir bin; cd bin; ln /c/ProgramData/chocolatey/lib/lua53/tools/lua53 lua; export PATH=$(pwd):$PATH; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir bin; cd bin; ln -s $(which lua5.3) lua; export PATH=$(pwd):$PATH; fi
  - lua -e "print 'working'"
deploy:
  provider: releases
  api_key:
    secure: oycC03K4KHCubDz8MfFXq4c9s1abJIpp/uPI9CwWRf4nf6RZ54+f/BYhcZhI66N7hsm5vtHJbuKSGyWRRBAWiKtdpqeEJVDuFL4KMi5MLecgb7NkKNLpmfeuqT3b+601YGl2C00phj5cMCcWeMlrzlqldO1MRjEIPOq7CLxoH8bCgIcycybY3MDQsfId+ObaVN3oOu8cb4R7IrVaX+IJASWfFv1RKDXT/9lXuJ0KQV0aEdXS773QpeFPj7JrnVbu6GPftQ9ct0dU3lnA+gPEk6wi047/e8gUxJiToo8fDXNp2YT/okus1gh07kp5kJmt5ArJphP3B+appFpBh97bA0fiXlVp+0YpauOKOJFSFO+HcAYwvkIxr7TpqradAmi6RkH14WnJLW6JiMqhRl96FDPkFqyAsi953sXNKpZjfDx0Far+ImDYDqW09kKxGOSpdEF/d/Dq+ps88gVZS73xz7LKWwq8KVVQiaIjV9wPnxx0WOXOwK/C9RrMc40QodKQWAz0Tn4wePLwi8CUPlLguNTu4wRRt2NQhAKjARCj4TdupANp2WpHBf9l8lCSBhIAMpbcPh8ob4cs2rNAlIn5eG0o7xycRQiIDi3/6QLY4oVfVE2Y5jBBXc4UJt7Xrqno5cmgYaolK9w2DyerkcVGWP9wIHpng+E5f92JjWTif74=
  file_glob: true
  file: lua-vfs-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true
